# Common variables
user: "{{ user_v }}"
user_uid: "{{ user_uid_v }}"
user_shell: "/bin/bash"
ssh_authorized_keys: "{{ ssh_authorized_keys_v }}"
permit_ssh_password_login: "yes"

# Domain and Certificates
domain: "{{ domain_v }}"
lan_range_cidr: "{{ lan_range_cidr_v }}"
lets_encrypt_dir: "/etc/letsencrypt/archive"

# Configuring Paths
root_install_dir: "{{ root_install_dir_v }}"
secrets_dir: "{{ root_install_dir }}/secrets"
scripts_dir: "{{ root_install_dir }}/scripts"

data_dir: "/mnt/critical"
backup_dir: "/mnt/backup"
data_mounts:
  - location: "{{ data_dir }}"
    owner: "root"
    mode: '0755'

docker_services_dir: "{{ root_install_dir }}/services"
docker_services_url: "git@github.com:clwhipp/docker-services.git"

yubikey_utils_dir: "/home/{{ user }}/workspace/yubikey-utils"
yubikey_utils_url: "git@github.com:clwhipp/yubikey-utils.git"

# Nebula Section
# nebula_service_restart: false
# nebula_lighthouse: "vpn.{{ domain }}"
# nebula_sign_enable: false
# nebula_sign_profile: ""
# nebula_is_lighthouse: false
# nebula_user: "nebula"
# nebula_install_dir: "/etc/nebula"
# nebula_tunnel_name: nebula1
# nebula_log_level: info
# nebula_port: "{{ nebula_port_v }}"
# nebula_range_cidr: "{{ nebula_range_cidr_v }}"
# nebula_inbound_rules:
# 
#   - port: "{{ ssh_port_v }}"
#     proto: tcp
#     group: acl:admin

# IPTables Section
