- name: Install borgbackup
  ansible.builtin.apt:
    name:
      - borgbackup
    state: present

- name: Deploying {{ borg_script_loc }}
  ansible.builtin.template:
    src: "backup-borg-template.sh.j2"
    dest: "{{ borg_script_loc }}"
    owner: root
    group: "root"
    mode: '0500'

- name: Enable rclone synchronization for {{ borg_script_loc }}
  include_role:
    name: configure_rclone_sync
    public: true
  vars:
    target: "{{ idrive_e2_target }}"
    access_key_id: "{{ idrive_e2_access_key_id }}"
    secret_access_key: "{{ idrive_e2_secret_access_key }}"
