- name: Ensure data directories exist for pihole
  file:
    path: "{{ item.location }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: "{{ item.mode }}"
  loop: "{{ pihole_data_mounts }}"

- name: Deploy PiHole .env file into environment
  ansible.builtin.template:
    src: "docker-env-template.j2"
    dest: "{{ docker_services_dir }}/ns/.env"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0400'

- name: Deploy PiHole Let's Encrypt
  include_role:
    name: configure_lets_encrypt_cloudflare
    public: true
  vars:
    account: "{{ svc_account }}"
    cert_domain: "{{ svc_domain }}"

- name: Set DNS to 1.1.1.1 in resolved.conf
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#?DNS='
    line: 'DNS=1.1.1.1'

- name: Disable DNSStubListener in resolved.conf
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#?DNSStubListener='
    line: 'DNSStubListener=no'

- name: Create symbolic link for resolv.conf
  ansible.builtin.file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: yes

- name: Restart systemd-resolved service
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
