- hosts: nexus
  become: true
  roles:
    - configure_all_services
    - configure_md_raid
    - configure_backups
    - configure_iptables

  vars:

  vars_files: 
    - ../vars/env-secrets.yml