- hosts: nexus
  become: true
  roles:
    - configure_tailscale
    - configure_jellyfin
    - configure_nextcloud
    - configure_vaultwarden
    - configure_code
    - configure_md_raid
    - configure_iptables
    - configure_wireguard

  vars:

  vars_files: 
    - ../vars/env-secrets.yml
