- hosts: nexus
  become: true
  roles:
    - configure_cockpit
    - configure_all_services
    - configure_lets_encrypt_cloudflare
    - configure_md_raid
    - configure_backups
    - configure_iptables

  vars:

    certificates:
      - domain: "files.{{ domain }}"
        account: "nc"
      - domain: "warden.{{ domain }}"
        account: "bw"

  vars_files: 
    - ../vars/env-secrets.yml