- hosts: media
  become: true
  roles:
    - common
    - configure_nebula
    - configure_docker
    - configure_jellyfin
    - configure_nfs_client
    - configure_iptables

  vars:
    # Nebula managed at the host level

    # Following is configuration for nfs_client role
    nfs_mount_script: "/home/{{ user }}/mount_nfs_shares.sh"
    nfs_server_address: "{{ nfs_server_ip }}"
    nfs_client_mounts:
      - share_name: "{{ data_dir }}/media"
        mount_point: "{{ data_dir }}/media"
      - share_name: "{{ data_dir }}/jellyfin"
        mount_point: "{{ data_dir }}/jellyfin"

  vars_files: 
    - vars/env-secrets.yml
