- name: Installing IPTable Restore Service
  ansible.builtin.copy:
    src: "iptables-restore.service"
    dest: "/etc/systemd/system/iptables-restore.service"
    owner: "root"
    group: "root"
    mode: '0700'

- name: Ensure scripts directory exists
  ansible.builtin.file:
    path: "{{ scripts_dir }}"
    state: directory
    owner: "root"
    group: "{{ user }}"
    mode: '0750'

- name: Install IPTables Setup Script
  ansible.builtin.template:
    src: "iptables-setup.sh.j2"
    dest: "{{ scripts_dir }}/iptables-setup.sh"
    owner: "root"
    group: "root"
    mode: '0500'

- name: Configuring IPTables
  command: "{{ scripts_dir }}/iptables-setup.sh"
