- name: Install rsync dependencies
  ansible.builtin.apt:
    name:
      - rsync
    state: present

- name: Deploy backup-critical-rsync.sh
  ansible.builtin.template:
    src: "backup-critical-rsync.sh.j2"
    dest: "{{ scripts_dir }}/backup-critical-rsync.sh"
    owner: root
    group: "root"
    mode: '0500'

- name: Adding Critical RAID rsync to crontab
  cron:
    name: "Critical RAID rsync"
    minute: "0"
    hour: "2"
    job: "{{ scripts_dir }}/backup-critical-rsync.sh"
    user: "root"

