all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
    servers:
      hosts:
        files:
          ansible_host: {{ files_ip_address }}
        media:
          ansible_host: {{ nebula_ip_address }}

