- name: Ensure code account exists
  ansible.builtin.user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    shell: "{{ item.shell | default(omit) }}"
    create_home: false
    state: present
  loop: "{{ code_linux_accounts }}"

- name: Ensure data directories exist
  file:
    path: "{{ item.location }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: "{{ item.mode }}"
  loop: "{{ code_data_mounts }}"

- name: Deploy Code .env file into environment
  ansible.builtin.template:
    src: "docker-env-template.j2"
    dest: "{{ docker_services_dir }}/code/.env"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0400'

- name: Deploy Code Let's Encrypt
  include_role:
    name: configure_lets_encrypt_cloudflare
    public: true
  vars:
    account: "{{ svc_account }}"
    cert_domain: "{{ svc_domain }}"
