- name: Check if cloudflare API token needs installed
  ansible.builtin.stat:
    path: "{{ secrets_dir }}/cloudflare.ini"
  register: cloudflare_auth_token

- name: Deploy cloudflare.ini for let's encrypt
  ansible.builtin.template:
    src: "cloudflare.ini.j2"
    dest: "{{ secrets_dir }}/cloudflare.ini"
    owner: "root"
    group: "root"
    mode: '0500'
  when: not cloudflare_auth_token.stat.exists

- name: Install packages for certbot and cloudflare integration
  ansible.builtin.apt:
    name:
      - python3-certbot-dns-cloudflare
      - python3-pip
    state: present

- name: Deploy let's encrypt script for {{ cert_domain }}
  ansible.builtin.template:
    src: "issue-certificate.sh.j2"
    dest: "{{ scripts_dir }}/issue-{{ cert_domain }}.sh"
    owner: "root"
    group: "root"
    mode: '0500'

- name: Ensure {{ lets_encrypt_dir }} exists with correct permissions
  file:
    path: "{{ lets_encrypt_dir }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "755"
