nebula_ca_sha: "{{ nebula_ca_sha_v }}"
nebula_service_restart: false
nebula_lighthouse: "vpn.{{ domain }}"
nebula_is_lighthouse: false
nebula_user: "nebula"
nebula_install_dir: "/etc/nebula"
nebula_tunnel_name: nebula1
nebula_log_level: info
nebula_port: "{{ nebula_port_v }}"
nebula_range_cidr: "{{ nebula_range_cidr_v }}"
nebula_cert_dir: "/home/{{ user }}/Certificates"
nebula_inject_keys: true
nebula_package_install: true
nebula_inbound_rules:

  - port: "{{ ssh_port_v }}"
    proto: tcp
    acl_group: admin

