- name: Ensure the user {{ nebula_user }} exists
  user:
    name: "{{ nebula_user }}"
    shell: /sbin/nologin
    uid: 2000
    create_home: yes
    state: present

- name: Setup Nebula Binaries
  import_tasks: package-installation.yml
  when: nebula_package_install

- name: Install Nebula Keys and Certificates
  import_tasks: key-installation.yml
  when: nebula_inject_keys

- name: Generate Host Configuration
  import_tasks: host-config.yml

- name: Deploy nebula systemd service
  ansible.builtin.template:
    src: nebula.service.j2
    dest: "/etc/systemd/system/nebula.service"
    owner: root
    group: root
    mode: '0644'

- name: Restart nebula service
  service:
    name: nebula
    state: restarted
  when: nebula_service_restart
