- name: Remove older versions of Docker
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  loop:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc

# Update the apt package index
- name: Update apt package index
  ansible.builtin.apt:
    update_cache: yes

# Install packages to allow apt to use a repository over HTTPS
- name: Install packages required for Docker
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

# Add Docker’s official GPG key
- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# Add Docker repository
- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

# Update the apt package index
- name: Update apt package index
  ansible.builtin.apt:
    update_cache: yes

- name: Install docker and docker compose packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Ensure the group 'docker' exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to the 'docker' group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: docker
    append: yes
