- name: Install Wireguard
  apt:
    name:
      - wireguard
      - wireguard-tools
    state: present

- name: Ensure /etc/wireguard directory exists
  file:
    path: /etc/wireguard
    state: directory
    owner: "root"
    group: "root"
    mode: '0700'

- name: Generate WireGuard configuration
  template:
    src: wireguard.conf.j2
    dest: "/etc/wireguard/{{ wg_interface }}.conf"
    owner: "root"
    group: "root"
    mode: '0600'

- name: Enable and start WireGuard
  systemd:
    name: wg-quick@{{ wg_interface }}
    enabled: yes
    state: started
