- name: Update apt package index
  ansible.builtin.apt:
    update_cache: yes

- name: Install git package
  ansible.builtin.apt:
    name:
      - git
    state: present

- name: Ensure .ssh directory exists for {{ user }}
  ansible.builtin.file:
    path: "/home/{{ user }}/.ssh"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0700'

- name: Installing Github SSH Key
  copy:
    src: "github_private_key.vault"
    dest: "/home/{{ user }}/.ssh/id_ed25519"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0700'

- name: Set user.name to {{ git_name_v }}
  git_config:
    name: user.name
    value: "{{ git_name_v }}"
    scope: global
  become: no

- name: Set user.email to {{ git_email_v }}
  git_config:
    name: user.email
    value: "{{ git_email_v }}"
    scope: global
  become: no
