- name: Update apt package index
  ansible.builtin.apt:
    update_cache: yes

- name: Install git package
  ansible.builtin.apt:
    name:
      - git
    state: present

- name: Ensure .ssh directory exists for {{ user }}
  ansible.builtin.file:
    path: "/home/{{ user }}/.ssh"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0700'

- name: Installing Github SSH Key
  copy:
    src: "github_private_key.vault"
    dest: "/home/{{ user }}/.ssh/id_ed25519"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0700'
