- name: Configure Hostname to {{ hostname }}
  hostname:
    name: "{{ hostname }}"

- name: Configure timezone to America/Chicago
  timezone:
    name: "America/Chicago"

- name: Setup SSH and Fail2Ban
  import_tasks: ssh.yml

- name: Setting up Git
  import_tasks: git.yml
