- name: Configure Hostname to {{ hostname }}
  hostname:
    name: "{{ hostname }}"

- name: Configure timezone to America/Chicago
  timezone:
    name: "America/Chicago"

- name: Install common packages
  ansible.builtin.apt:
    name:
      - cron
      - tmux
      - vim
    state: present

- name: Ensure base directories exist
  file:
    path: "{{ item.location }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ data_directories }}"

- name: Setup SSH and Fail2Ban
  import_tasks: ssh.yml

- name: Setting up Git
  import_tasks: git.yml
