
- name: Ensure .ssh directory exists
  file:
    path: "/home/{{ user }}/.ssh"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0700'

- name: Set authorized keys
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ item }}"
  with_items: "{{ ssh_authorized_keys }}"

- name: Deploy custom sshd_config
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
  # notify: restart sshd

- name: Install Fail2Ban for ssh
  ansible.builtin.apt:
    name: "fail2ban"
    state: present

- name: Copy jail.conf to jail.local for Fail2Ban
  ansible.builtin.copy:
    src: /etc/fail2ban/jail.conf
    dest: /etc/fail2ban/jail.local
    force: no
    remote_src: yes
    owner: root
    group: root
    mode: '0644'

- name: Ensure fail2ban directory exists
  file:
    path: "/etc/fail2ban/jail.d"
    state: directory

- name: Deploy custom fail2ban for ssh
  ansible.builtin.template:
    src: sshd_fail2ban.j2
    dest: /etc/fail2ban/jail.d/sshd.conf
    owner: root
    group: root
    mode: '0644'
  # notify: restart fail2ban
