- name: Ensure vars directory exists
  file:
    path: "{{ root_install_dir }}/vars"
    state: directory
    owner: "root"
    group: "root"
    mode: "700"

- name: Deploy {{ root_install_dir }}/vars/all-envvars.sh
  ansible.builtin.template:
    src: "envvars.sh.j2"
    dest: "{{ root_install_dir }}/vars/all-envvars.sh"
    owner: "root"
    group: "root"
    mode: '0400'
