ansible_become_pass: "{{ lookup('bitwarden_password', 'code_linux_user_password') }}"

# Common Overrides
hostname: "code"
fqdn: "{{ hostname }}.{{ domain }}"
user_password: "{{ lookup('bitwarden_field', 'hash', 'code_linux_user_password') }}"

# Nebula Configurations
nebula_service_restart: false
nebula_sign_enable: true
nebula_sign_profile: "{{ fqdn }}"
nebula_install_dir: "/etc/nebula"
nebula_inbound_rules:

  - port: "{{ ssh_port }}"
    proto: tcp
    group: acl:admin

  - port: "443"
    proto: tcp
    group: acl:dev

  - port: "80"
    proto: tcp
    group: acl:dev

  - port: "8080"
    proto: tcp
    group: acl:dev

  - port: "8096"
    proto: tcp
    group: acl:dev

  - port: "8443"
    proto: tcp
    group: acl:dev

  - port: "9000"
    proto: tcp
    group: acl:dev

  - port: "{{ ssh_port }}"
    proto: tcp
    group: admin

  - port: "443"
    proto: tcp
    group: dev

  - port: "80"
    proto: tcp
    group: dev

  - port: "8080"
    proto: tcp
    group: dev

  - port: "8096"
    proto: tcp
    group: dev

  - port: "8443"
    proto: tcp
    group: dev

  - port: "9000"
    proto: tcp
    group: dev
