ansible_become_pass: "{{ lookup('bitwarden_password', 'code_linux_user_password') }}"

# Common Overrides
hostname: "code"
fqdn: "{{ hostname }}.{{ domain }}"
user_password: "{{ lookup('bitwarden_field', 'hash', 'code_linux_user_password') }}"
