ansible_become_pass: "{{ lookup('bitwarden_password', 'files_linux_user_password') }}"

# Common Overrides
hostname: "files"
fqdn: "{{ hostname }}.{{ domain }}"
user_password: "{{ lookup('bitwarden_field', 'hash', 'files_linux_user_password') }}"

# Nebula Configurations
nebula_restart_service: true
nebula_sign_enable: true
nebula_sign_profile: "{{ fqdn }}"
nebula_inbound_rules:

  - port: "{{ ssh_port_v }}"
    proto: tcp
    group: acl:admin

  - port: 443
    proto: tcp
    group: acl:nextcloud

  - port: 8443
    proto: tcp
    group: acl:nextcloud

  - port: "{{ ssh_port_v }}"
    proto: tcp
    group: admin

  - port: 443
    proto: tcp
    group: nextcloud

  - port: 8443
    proto: tcp
    group: nextcloud


# Service Configurations
service_linux_accounts:
  - name: "nc"
    uid: 1502
    shell: "/sbin/nologin"
  - name: "db"
    uid: 1503
    shell: "/sbin/nologin"

data_mounts:
  - location: "{{ data_dir }}"
    owner: "root"
    mode: '0755'
  - location: "{{ data_dir }}/nextcloud"
    owner: "nc"
    mode: '0700'
  - location: "{{ data_dir }}/mariadb"
    owner: "db"
    mode: '0700'

# Certificate Signing Request Section
csr_cn: "Nextcloud"
svc_domain: "{{ fqdn }}"
svc_account: "nc"
