ansible_become_pass: "{{ lookup('bitwarden_password', 'media_linux_user_password') }}"

# Common Overrides
hostname: "media"
fqdn: "{{ hostname }}.{{ domain }}"
user_password: "{{ lookup('bitwarden_field', 'hash', 'media_linux_user_password') }}"

# Nebula Configurations
nebula_restart_service: true
nebula_sign_enable: true
nebula_sign_profile: "{{ fqdn }}"
nebula_inbound_rules:

  - port: "{{ ssh_port }}"
    proto: tcp
    group: acl:admin

  - port: "{{ ssh_port }}"
    proto: tcp
    group: acl:uploader

  - port: 80
    proto: tcp
    group: acl:media

  - port: 8096
    proto: tcp
    group: acl:media    

  - port: "{{ ssh_port }}"
    proto: tcp
    group: admin

  - port: 80
    proto: tcp
    group: media

  - port: 8096
    proto: tcp
    group: media

data_mounts:
  - location: "{{ data_dir }}"
    owner: "root"
    mode: '0755'
  - location: "{{ data_dir }}/media"
    owner: "media"
    mode: '0700'
  - location: "{{ data_dir }}/jellyfin"
    owner: "media"
    mode: '0700'
