ansible_become_pass: "{{ lookup('bitwarden_password', 'nexus_linux_user_password') }}"
user_password: "{{ lookup('bitwarden_field', 'hash', 'nexus_linux_user_password') }}"

# Common Overrides
hostname: "nexus"
fqdn: "{{ hostname }}.{{ domain }}"
