ansible_become_pass: "{{ lookup('bitwarden_password', 'warden_linux_user_password') }}"

# Common Overrides
hostname: "warden"
fqdn: "{{ hostname }}.{{ domain }}"
user_password: "{{ lookup('bitwarden_field', 'hash', 'warden_linux_user_password') }}"

# Nebula Configurations
nebula_service_restart: false
nebula_sign_enable: true
nebula_sign_profile: "{{ fqdn }}"
nebula_install_dir: "/mnt/nebula"
nebula_inbound_rules:

  - port: "{{ ssh_port_v }}"
    proto: tcp
    group: acl:admin

  - port: 443
    proto: tcp
    group: acl:bitwarden

  - port: 8080
    proto: tcp
    group: acl:bitwarden

  - port: 3012
    proto: tcp
    group: acl:bitwarden

  - port: "{{ ssh_port_v }}"
    proto: tcp
    group: admin

  - port: 443
    proto: tcp
    group: bitwarden

  - port: 8080
    proto: tcp
    group: bitwarden

  - port: 3012
    proto: tcp
    group: bitwarden

# Service Configurations
service_linux_accounts:
  - name: "bw"
    uid: 1500
    shell: "/sbin/nologin"

data_mounts:
  - location: "{{ data_dir }}"
    owner: "root"
    mode: '0755'
  - location: "{{ data_dir }}/bitwarden"
    owner: "bw"
    mode: '0700'

# Certificate Signing Request Section
csr_cn: "Bitwarden"
svc_domain: "{{ fqdn }}"
