- name: Ensure {{ root_install_dir }} exists
  file:
    path: "{{ root_install_dir }}"
    state: directory
    owner: "root"
    group: "{{ user }}"
    mode: '0750'

- name: Ensure service accounts exist
  ansible.builtin.user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    shell: "{{ item.shell | default(omit) }}"
    create_home: false
    state: present
  loop: "{{ nextcloud_linux_accounts }}"

- name: Ensure data directories exist
  file:
    path: "{{ item.location }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: "{{ item.mode }}"
  loop: "{{ nextcloud_data_mounts }}"

- name: Deploy Nextcloud .env file into environment
  ansible.builtin.template:
    src: "docker-env-template.j2"
    dest: "{{ docker_services_dir }}/nc/.env"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0400'

- name: Ensure {{ scripts_dir }} exists
  file:
    path: "{{ scripts_dir }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "755"

- name: Update apt package index
  ansible.builtin.apt:
    update_cache: yes

- name: Install MySQL Client for Backups
  ansible.builtin.apt:
    name:
      - mysql-client
    state: present

- name: Deploy backup-nextcloud-mariadb.sh script
  ansible.builtin.template:
    src: "backup-nextcloud-mariadb.sh.j2"
    dest: "{{ scripts_dir }}/backup-nextcloud-mariadb.sh"
    owner: root
    group: "root"
    mode: '0500'
