- name: Ensure service accounts exist
  ansible.builtin.user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    shell: "{{ item.shell | default(omit) }}"
    create_home: false
    state: present
  loop: "{{ nextcloud_linux_accounts }}"

- name: Ensure data directories exist
  file:
    path: "{{ item.location }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: "{{ item.mode }}"
  loop: "{{ nextcloud_data_mounts }}"

- name: Deploy Nextcloud .env file into environment
  ansible.builtin.template:
    src: "docker-env-template.j2"
    dest: "{{ docker_services_dir }}/nc/.env"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0400'

- name: Install MySQL Client for Backups
  ansible.builtin.apt:
    name:
      - mysql-client
    state: present

- name: Deploy backup-nextcloud-mariadb.sh script
  ansible.builtin.template:
    src: "backup-nextcloud-mariadb.sh.j2"
    dest: "{{ scripts_dir }}/backup-nextcloud-mariadb.sh"
    owner: "root"
    group: "root"
    mode: '0500'

- name: Enable Nextcloud Backups
  include_role:
    name: configure_borg_backup
    public: true
  vars:
    # Borg - Encryption
    borg_src_dir: "{{ data_dir }}/nextcloud"
    borg_repo_dir: "{{ backup_dir }}/borg"
    borg_bws_secret_uid: "{{ lookup('bitwarden_field', 'bws_secret_uid', 'borg - nextcloud') }}"
    borg_script_loc: "{{ scripts_dir }}/backup-borg-nextcloud.sh"

    # IDrive E2 - Offsite Storage
    idrive_e2_target: "idrive-e2-nextcloud"
    idrive_e2_bucket: "borg-production"
    idrive_e2_access_key_id: "{{ lookup('bitwarden_field', 'rclone_access_key_id', 'borg - nextcloud') }}"
    idrive_e2_secret_access_key: "{{ lookup('bitwarden_field', 'rclone_secret_access_key', 'borg - nextcloud') }}"

- name: Deploy Nextcloud Let's Encrypt
  include_role:
    name: configure_lets_encrypt_cloudflare
    public: true
  vars:
    account: "{{ svc_account }}"
    cert_domain: "{{ svc_domain }}"
