- name: Ensure {{ root_install_dir }} exists
  file:
    path: "{{ root_install_dir }}"
    state: directory
    owner: "root"
    group: "{{ user }}"
    mode: '0750'

- name: Ensure Vaultwarden accounts exist
  ansible.builtin.user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    shell: "{{ item.shell | default(omit) }}"
    create_home: false
    state: present
  loop: "{{ vaultwarden_linux_accounts }}"

- name: Ensure data directories exist for vaultwarden
  file:
    path: "{{ item.location }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: "{{ item.mode }}"
  loop: "{{ vaultwarden_data_mounts }}"

- name: Deploy Vaultwarden .env file into environment
  ansible.builtin.template:
    src: "docker-env-template.j2"
    dest: "{{ docker_services_dir }}/bw/.env"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0400'
