- name: Update apt package index
  ansible.builtin.apt:
    update_cache: yes

- name: Installing yubikey-luks dependencies
  ansible.builtin.apt:
    name:
      - cryptsetup
      - initramfs-tools
      - yubikey-personalization
    state: present

- name: Setup yubikey-luks repository
  import_tasks: repo.yml
