- name: Install rclone dependencies
  ansible.builtin.apt:
    name:
      - unzip
    state: present

- name: Download the latest rlcone package
  get_url:
    url: "https://downloads.rclone.org/rclone-current-linux-amd64.zip"
    dest: "/home/{{ user }}/workspace/rclone-latest.zip"
    mode: '0600'

- name: Unzip the rclone package
  unarchive:
    src: "/home/{{ user }}/workspace/rclone-latest.zip"
    dest: "/home/{{ user }}/workspace/rclone_setup"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "755"
    remote_src: yes

- name: Find the sub-directory created after unzipping
  find:
    paths: "/home/{{ user }}/workspace/rclone_setup"
    file_type: directory
    depth: 1
  register: subdir

- name: Set fact for sub-directory name
  set_fact:
    subdir_name: "{{ subdir.files[0].path }}"

- name: Copy rclone binary into /usr/bin
  copy:
    src: "{{ subdir_name }}/rclone"
    dest: "/usr/bin"
    owner: "root"
    group: "root"
    mode: "755"
    remote_src: yes

- name: Delete a directory
  file:
    path: "/home/{{ user }}/workspace/rclone_setup"
    state: absent

- name: Adding {{ idrive_e2_target }} credentials into rclone configuration
  rclone_config:
    idrive_e2_target: "{{ idrive_e2_target }}"
    idrive_e2_access_key_id: "{{ idrive_e2_access_key_id }}"
    idrive_e2_secret_access_key: "{{ idrive_e2_secret_access_key }}"

- name: Ensure rclone configuration permissions are correct
  file:
    path: "/root/.config/rclone/rclone.conf"
    state: file
    owner: "root"
    group: "root"
    mode: '0700'
