- name: Ensure {{ root_install_dir }} exists
  file:
    path: "{{ root_install_dir }}"
    state: directory
    owner: "root"
    group: "{{ user }}"
    mode: '0750'

- name: Ensure jellyfin linux accounts exist
  ansible.builtin.user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    shell: "{{ item.shell | default(omit) }}"
    password: "{{ item.password }}"
    create_home: false
    state: present
  loop: "{{ jellyfin_linux_accounts }}"

- name: Ensure Jellyfin data directories exist
  file:
    path: "{{ item.location }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: "{{ item.mode }}"
  loop: "{{ jellyfin_data_mounts }}"

- name: Ensure media .ssh directory exists
  file:
    path: "/home/media/.ssh"
    state: directory
    owner: "media"
    group: "media"
    mode: '0700'

- name: Set authorized keys for media
  authorized_key:
    user: "media"
    state: present
    key: "{{ item }}"
  with_items: "{{ ssh_authorized_keys }}"

- name: Deploy {{ root_install_dir }}/envvars.sh
  ansible.builtin.template:
    src: "envvars.sh.j2"
    dest: "{{ root_install_dir }}/envvars.sh"
    owner: "root"
    group: "root"
    mode: '0400'
