- name: Install bitwarden secrets manager dependencies
  ansible.builtin.apt:
    name:
      - unzip
      - jq
    state: present

- name: Check if bws already installed
  stat:
    path: /usr/bin/bws
  register: bws_stat

- name: Downloading Bitwarden Secrets Manager CLI
  get_url:
    url: https://github.com/bitwarden/sdk/releases/download/bws-v0.5.0/bws-x86_64-unknown-linux-gnu-0.5.0.zip
    dest: "/home/{{ user }}/workspace/bws.zip"
    mode: '0600'
  when: not bws_stat.stat.exists

- name: Unzipping Bitwarden Secrets Manager Archive
  unarchive:
    src: "/home/{{ user }}/workspace/bws.zip"
    dest: /usr/bin
    remote_src: yes
  when: not bws_stat.stat.exists

- name: Adjust ownership and permissions
  file:
    path: "/usr/bin/bws"
    owner: root
    group: root
    mode: '0755'
  when: not bws_stat.stat.exists

- name: Check if bws token file present
  ansible.builtin.stat:
    path: "{{ secrets_dir }}/.bws-token.sh"
  register: bws_secret_present

- name: Downloading Biwarden Secrets Access Key
  ansible.builtin.copy:
    src: "bws-token.sh"
    dest: "{{ secrets_dir }}/.bws-token.sh"
    owner: root
    group: root
    mode: '700'
  when: not bws_secret_present.stat.exists
